name: streamlit
services:
    streamlit-music-vis:
        container_name: streamlit
        # command: streamlit run Galgalaz_Vis.py --logger.level=debug
        environment:
            - SPOTIPY_CLIENT_ID=${SPOTIPY_ID}
            - SPOTIPY_CLIENT_SECRET=${SPOTIPY_SECRET}
        volumes:
            - ./src:/app
            - ./data:/data
        ports:
            - 8501:8501
        image: rfabian665/streamlit-music-vis