name: streamlit
services:
    streamlit-music-vis:
        container_name: streamlit
        environment:
            - SPOTIPY_CLIENT_ID=$env:SPOTIPY_CLIENT_ID
            - SPOTIPY_CLIENT_SECRET=$env:SPOTIPY_CLIENT_SECRET
        volumes:
            - ./src:/app
        ports:
            - 8501:8501
        image: streamlit-music-vis